import { useApp } from '@renderer/app/AppContext'
import { t as trainerT, skillLabel, type Lang, type StringKey } from '@renderer/app/i18n'
import type { Skill } from '@shared/types'

/** Strings only the Office view uses. Shared study wording comes from the trainer's i18n. */
const en = {
  workspace: 'toeic-prep',
  newThread: 'New thread',
  groupPart5: 'Part 5 · grammar',
  groupReading: 'Part 7 · reading',
  groupTests: 'Tests',
  status: 'Status',
  readingAll: 'All passages',
  composerAnswer: 'Reply A–D, or type / for commands',
  composerNext: 'Enter for the next task · / for commands',
  composerIdle: 'Type / for commands',
  composerPick: 'Pick a set, Enter for a random one · / for commands',
  composerTest: 'Reply A–D · ← → to move · F to flag · / for commands',
  explainPill: 'explain',
  send: 'Send',
  thinking: 'Checking',
  answerIs: 'answer: {x}',
  recorded: 'Recorded. Explanations come at the end.',
  doneHead: 'Done · {c} of {n} correct',
  avg: 'avg {s}s',
  over: 'over {s}s pace',
  missed: 'Tested points you missed',
  allCorrect: 'No misses this run.',
  nextWeakest: 'Drill {topic}',
  home: 'New thread',
  homeLeadTest: 'You have an unfinished Reading test.',
  homeDueHead: '{n} due for review',
  evidence: 'Evidence',
  allTopics: 'All {n} topics',
  fewerTopics: 'Fewer topics',
  sugResume: 'Resume Reading test',
  sugResumeMeta: '{a}/{n} answered · {m} min left',
  sugReview: 'Review due items',
  sugDrill: 'Drill {topic}',
  sugDrillMeta: '{p}% lately',
  sugDrillNew: 'new',
  sugRead: 'Read a single-passage set',
  sugMixed: 'Mixed test · Part 5 + 6',
  sugStatus: 'Status report',
  suggested: 'Suggested',
  pickIntro: 'Pick a set to open, or press Enter for a random one.',
  pickRandom: 'Random set',
  pickNone: 'No sets match this filter yet.',
  anotherSet: 'Another set',
  backToSets: 'All sets',
  pane: 'Document',
  paneShow: 'Show document',
  paneHide: 'Hide document',
  sidebarShow: 'Show threads',
  sidebarHide: 'Hide threads',
  mapTitle: 'Questions',
  mapSummary: '{a} answered · {f} flagged · {u} left',
  testRunning: 'running',
  testPaused: 'paused while hidden',
  submitAsk: '{n} questions are unanswered. Submit anyway?',
  resultsHead: 'Reading test finished',
  reviewAll: 'Every question',
  reviewHint: 'Open a row to see the explanation.',
  statusHead: 'Status report',
  statusGrammar: 'Grammar topics (Part 5 + 6)',
  statusReading: 'Reading question types (Part 7)',
  statusRecent: 'Recent tests',
  statusMixedRow: 'Mixed test',
  statusTestRow: 'Reading test ({length})',
  settingsHead: 'Settings',
  theme: 'Theme',
  themeHint: 'Dark keeps the screen dim on an office desk. Light suits a bright room.',
  themeDark: 'Dark',
  themeLight: 'Light',
  bossKey: 'Boss key',
  bossKeyHint: 'Hides the window from the screen and the taskbar. Press it again to bring the window back. A running Reading test pauses while hidden.',
  view: 'View',
  viewHint: 'Ctrl+Shift+M switches views any time. To open straight into Office, start the app with the --office flag.',
  viewSwitch: 'Switch to Trainer view',
  shortcuts: 'Shortcuts',
  kNew: 'New thread',
  kSidebar: 'Show or hide threads',
  kCommands: 'Commands',
  kView: 'Switch view',
  kHide: 'Hide window',
  unknownCommand: 'Unknown command {c}. Type / to see the list.',
  needArg: '{c} needs one of: {list}',
  badAnswer: 'Answer with A, B, C or D.',
  cmdReview: 'Review items due today',
  cmdDrill: 'Drill a Part 5 topic',
  cmdRead: 'Open Part 7 passages',
  cmdMixed: 'Mixed test, Part 5 + 6',
  cmdTest: 'Timed Reading test',
  cmdStatus: 'Progress report',
  cmdSettings: 'Settings',
  cmdLang: 'Explanation language',
  cmdTheme: 'Dark or light theme',
  cmdTrainer: 'Switch to Trainer view',
  cmdNew: 'New thread',
  cmdNext: 'Next task',
  cmdAgain: 'Run this again',
  cmdRandom: 'Open a random set',
  cmdPrev: 'Previous question',
  cmdFlag: 'Flag or unflag this question',
  cmdGoto: 'Jump to a question number',
  cmdSubmit: 'Submit the test',
  langTh: 'Thai',
  langEn: 'English'
} as const

export type OfficeKey = keyof typeof en

const th: Record<OfficeKey, string> = {
  workspace: 'toeic-prep',
  newThread: 'เธรดใหม่',
  groupPart5: 'Part 5 · ไวยากรณ์',
  groupReading: 'Part 7 · การอ่าน',
  groupTests: 'ข้อสอบ',
  status: 'สถานะ',
  readingAll: 'บทความทั้งหมด',
  composerAnswer: 'ตอบ A–D หรือพิมพ์ / เพื่อดูคำสั่ง',
  composerNext: 'Enter ไปข้อต่อไป · / ดูคำสั่ง',
  composerIdle: 'พิมพ์ / เพื่อดูคำสั่ง',
  composerPick: 'เลือกชุด หรือกด Enter เพื่อสุ่ม · / ดูคำสั่ง',
  composerTest: 'ตอบ A–D · ← → เลื่อนข้อ · F ทำเครื่องหมาย · / ดูคำสั่ง',
  explainPill: 'คำอธิบาย',
  send: 'ส่ง',
  thinking: 'กำลังตรวจ',
  answerIs: 'คำตอบ: {x}',
  recorded: 'บันทึกแล้ว คำอธิบายจะแสดงตอนจบ',
  doneHead: 'เสร็จแล้ว · ถูก {c} จาก {n} ข้อ',
  avg: 'เฉลี่ย {s} วิ',
  over: 'เกิน {s} วิ',
  missed: 'จุดที่ออกสอบที่ยังพลาด',
  allCorrect: 'รอบนี้ไม่พลาดเลย',
  nextWeakest: 'ฝึก {topic}',
  home: 'เธรดใหม่',
  homeLeadTest: 'มีข้อสอบ Reading ที่ยังทำไม่เสร็จ',
  homeDueHead: 'ทบทวน {n} ข้อ',
  evidence: 'หลักฐาน',
  allTopics: 'ดูทั้ง {n} หัวข้อ',
  fewerTopics: 'ย่อรายการหัวข้อ',
  sugResume: 'ทำข้อสอบ Reading ต่อ',
  sugResumeMeta: 'ตอบแล้ว {a}/{n} · เหลือ {m} นาที',
  sugReview: 'ทบทวนข้อที่ถึงกำหนด',
  sugDrill: 'ฝึก {topic}',
  sugDrillMeta: 'ช่วงหลังถูก {p}%',
  sugDrillNew: 'ยังไม่เคยฝึก',
  sugRead: 'อ่านบทความเดียวหนึ่งชุด',
  sugMixed: 'แบบทดสอบรวม · Part 5 + 6',
  sugStatus: 'รายงานสถานะ',
  suggested: 'แนะนำ',
  pickIntro: 'เลือกชุดที่จะเปิด หรือกด Enter เพื่อสุ่ม',
  pickRandom: 'สุ่มชุด',
  pickNone: 'ยังไม่มีชุดที่ตรงกับตัวกรองนี้',
  anotherSet: 'ชุดอื่น',
  backToSets: 'ทุกชุด',
  pane: 'เอกสาร',
  paneShow: 'แสดงเอกสาร',
  paneHide: 'ซ่อนเอกสาร',
  sidebarShow: 'แสดงรายการเธรด',
  sidebarHide: 'ซ่อนรายการเธรด',
  mapTitle: 'ข้อสอบทั้งหมด',
  mapSummary: 'ตอบแล้ว {a} · ทำเครื่องหมาย {f} · เหลือ {u}',
  testRunning: 'กำลังทำ',
  testPaused: 'หยุดเวลาขณะซ่อน',
  submitAsk: 'ยังไม่ได้ตอบ {n} ข้อ ต้องการส่งเลยหรือไม่',
  resultsHead: 'ทำข้อสอบ Reading เสร็จแล้ว',
  reviewAll: 'ทุกข้อ',
  reviewHint: 'เปิดแต่ละแถวเพื่อดูคำอธิบาย',
  statusHead: 'รายงานสถานะ',
  statusGrammar: 'หัวข้อไวยากรณ์ (Part 5 + 6)',
  statusReading: 'ประเภทคำถามการอ่าน (Part 7)',
  statusRecent: 'ข้อสอบล่าสุด',
  statusMixedRow: 'แบบทดสอบรวม',
  statusTestRow: 'ข้อสอบ Reading ({length})',
  settingsHead: 'ตั้งค่า',
  theme: 'ธีม',
  themeHint: 'โทนมืดช่วยให้หน้าจอไม่สว่างเด่นบนโต๊ะทำงาน โทนสว่างเหมาะกับห้องที่มีแสงมาก',
  themeDark: 'มืด',
  themeLight: 'สว่าง',
  bossKey: 'ปุ่มซ่อนด่วน',
  bossKeyHint: 'ซ่อนหน้าต่างออกจากหน้าจอและแถบงาน กดอีกครั้งเพื่อเปิดกลับมา ข้อสอบ Reading ที่กำลังทำจะหยุดเวลาระหว่างซ่อน',
  view: 'มุมมอง',
  viewHint: 'กด Ctrl+Shift+M เพื่อสลับมุมมองได้ทุกเมื่อ หากต้องการเปิดเข้ามุมมองออฟฟิศทันที ให้เปิดแอปด้วยแฟล็ก --office',
  viewSwitch: 'สลับไปมุมมองแบบฝึกปกติ',
  shortcuts: 'คีย์ลัด',
  kNew: 'เธรดใหม่',
  kSidebar: 'แสดงหรือซ่อนรายการเธรด',
  kCommands: 'คำสั่ง',
  kView: 'สลับมุมมอง',
  kHide: 'ซ่อนหน้าต่าง',
  unknownCommand: 'ไม่รู้จักคำสั่ง {c} พิมพ์ / เพื่อดูรายการ',
  needArg: '{c} ต้องระบุหนึ่งใน: {list}',
  badAnswer: 'ตอบด้วย A, B, C หรือ D',
  cmdReview: 'ทบทวนข้อที่ถึงกำหนดวันนี้',
  cmdDrill: 'ฝึกหัวข้อ Part 5',
  cmdRead: 'เปิดบทความ Part 7',
  cmdMixed: 'แบบทดสอบรวม Part 5 + 6',
  cmdTest: 'ข้อสอบ Reading จับเวลา',
  cmdStatus: 'รายงานความก้าวหน้า',
  cmdSettings: 'ตั้งค่า',
  cmdLang: 'ภาษาของคำอธิบาย',
  cmdTheme: 'ธีมมืดหรือสว่าง',
  cmdTrainer: 'สลับไปมุมมองแบบฝึกปกติ',
  cmdNew: 'เธรดใหม่',
  cmdNext: 'ข้อต่อไป',
  cmdAgain: 'ทำชุดนี้อีกครั้ง',
  cmdRandom: 'เปิดชุดแบบสุ่ม',
  cmdPrev: 'ข้อก่อนหน้า',
  cmdFlag: 'ทำหรือเอาเครื่องหมายออก',
  cmdGoto: 'ไปยังข้อที่ระบุ',
  cmdSubmit: 'ส่งข้อสอบ',
  langTh: 'ไทย',
  langEn: 'อังกฤษ'
}

const STRINGS: Record<Lang, Record<OfficeKey, string>> = { en, th }

const fill = (s: string, vars: Record<string, string | number>) =>
  s.replace(/\{(\w+)\}/g, (_, name: string) => String(vars[name] ?? `{${name}}`))

export function useO() {
  const lang: Lang = useApp().settings.language
  return {
    lang,
    o: (key: OfficeKey, vars: Record<string, string | number> = {}) => fill(STRINGS[lang][key], vars),
    t: (key: StringKey, vars?: Record<string, string | number>) => trainerT(lang, key, vars),
    skill: (s: Skill) => skillLabel(s, lang)
  }
}
